[project]
name = "ssl_checker_api"
version = "1.0.1.0"
description = "API wrapper for SSL certificate checker"
authors = ["voidmoose <voidmoose@voidmoose.com>"]
readme = "README.md"
requires-python = ">=3.8"
license = "Apache 2.0"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/sxmxc/ssl_checker_api"
Issues = "https://github.com/sxmxc/ssl_checker_api/issues"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
testpaths = [
    "tests",
]
filterwarnings = [ 
	"error",
    "ignore::UserWarning",
    "ignore::PendingDeprecationWarning"
]