name: Docker Image CI

on: 
  push:
    tags:
      - 'v*.*.*.*'  # Triggers on semantic version tags like v1.0.0.0, v2.1.3.1, etc.
env:
    IMAGE_NAME: ssl_checker_api
    
jobs:
  set-version:
    name: Set Version
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch complete history for accurate commit counting
          lfs: true
          
      - name: Generate Build Info
        id: get_version
        run: |
          # Extract version number from git tag (removes 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          
          # Generate build number from total commit count
          BUILD_NUMBER=$(git rev-list --count HEAD)
          
          # Make these values available to other jobs
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          
          # Log the values for debugging
          echo "Version: $VERSION"
          echo "Build Number: $BUILD_NUMBER"
          
  docker:
    environment: default
    needs: set-version
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:v${{ needs.set-version.outputs.version }}
